//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSON_WEB_API2
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaihang
    {
        public loaihang()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        public int ID { get; set; }
        public string TENLOAI { get; set; }
        public string MOTA { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
    
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
