//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MSON
{
    using System;
    using System.Collections.Generic;

    public partial class loaihang
    {
        public loaihang()
        {
            this.sanphams = new HashSet<sanpham>();
        }
        [Display(Name = "Mã loại sản phẩm")]
        public int ID { get; set; }
        [Display(Name = "Tên loại sản phẩm")]
        public string TENLOAI { get; set; }
        [Display(Name = "Mô tả loại sản phẩm")]
        public string MOTA { get; set; }
        [Display(Name = "Ngày nhập loại")]
        public Nullable<System.DateTime> NGAYNHAP { get; set; }

        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
