//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSON
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class nguoidung
    {
        [Required(ErrorMessage="Không được để trống !")]
        [Display(Name = "Tên đăng nhập")]
        public string tendangnhap { get; set; }


        [Required(ErrorMessage = "Không được để trống !")]
         [Display(Name = "Mật khẩu")]
        public string matkhau { get; set; }
    }
}
