//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MSON
{
    using System;
    using System.Collections.Generic;

    public partial class nguoidung
    {
        [DisplayName("Tên đăng nhập")]
        public string tendangnhap { get; set; }
        [DisplayName("Mật khẩu")]
        public string matkhau { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
    }
}
