//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MSON
{
    using System;
    using System.Collections.Generic;

    public partial class sanpham
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !")]
        [Display(Name = "Tên sản phẩm")]
        public string TEN { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !")]
        [Display(Name = "Mô tả")]
        public string MOTA { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !")]
        [Display(Name = "Ngày nhập")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !")]
        [Display(Name = "Loại sản phẩm")]
        public Nullable<int> ID_LOAIHANG { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !")]
        [Display(Name = "Hình ảnh")]
        public string IMG_URL { get; set; }

        public virtual loaihang loaihang { get; set; }
    }
}
